SELECT TO_CHAR(SALES_DATE,'YYYY') YEAR
    ,TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) MONTH
    ,GENDER
    ,COUNT(DISTINCT A.USER_ID) USERS
FROM ONLINE_SALE A
JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'),TO_CHAR(SALES_DATE,'MM'),GENDER
ORDER BY YEAR, MONTH, GENDER
