SELECT CART_ID 
FROM
(SELECT CART_ID
,LISTAGG(NAME,',') WITHIN GROUP (ORDER BY CART_ID) AS LIST
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING LISTAGG(NAME,',') WITHIN GROUP (ORDER BY CART_ID) LIKE '%Milk%' 
    AND LISTAGG(NAME,',') WITHIN GROUP (ORDER BY CART_ID) LIKE '%Yogurt%'
ORDER BY CART_ID)