SELECT HOUR, COUNT(T1.DATETIME) AS COUNT
FROM
    (SELECT LEVEL-1 AS HOUR
        FROM DUAL
        CONNECT BY LEVEL <= 24) T2 LEFT JOIN ANIMAL_OUTS T1
    ON T2.HOUR = TO_CHAR(T1.DATETIME, 'HH24')
GROUP BY HOUR
ORDER BY HOUR ASC