SELECT FLAVOR FROM 
    (SELECT A.FLAVOR FLAVOR, SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) SUM
    FROM FIRST_HALF A
    JOIN JULY B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY SUM DESC)
WHERE ROWNUM <=3