SELECT * FROM 
    (SELECT A.NAME, A.DATETIME FROM ANIMAL_INS A
        LEFT JOIN ANIMAL_OUTS B ON
        A.ANIMAL_ID = B.ANIMAL_ID
        WHERE B.NAME IS NULL 
        ORDER BY DATETIME )
WHERE NAME IS NOT NULL AND ROWNUM <= 3