SELECT MAX(CATEGORY) KEEP(DENSE_RANK FIRST ORDER BY PRICE DESC) CATEGORY,
    MAX(PRICE) MAX_PRICE,
    MAX(PRODUCT_NAME) KEEP(DENSE_RANK FIRST ORDER BY PRICE DESC) PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY LIKE '%과자%' 
    OR CATEGORY LIKE '%국%' 
    OR CATEGORY LIKE '%김치%' 
    OR CATEGORY LIKE '%식용유%'
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC