SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW B
JOIN MEMBER_PROFILE A
ON A.MEMBER_ID = B.MEMBER_ID
JOIN (SELECT MEMBER_ID FROM                      
          (SELECT RANK() OVER(PARTITION BY MEMBER_ID ORDER BY ROWNUM DESC) RANK, MEMBER_ID
          FROM REST_REVIEW
          ORDER BY RANK DESC)
     WHERE ROWNUM BETWEEN 1 AND 1) C
ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
