SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,SUM(C.SALES * A.PRICE) TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN (SELECT BOOK_ID, SALES FROM BOOK_SALES 
        WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01') C
ON A.BOOK_ID = C.BOOK_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC