SELECT CAR_ID
    ,MAX(CASE WHEN TO_CHAR(START_DATE,'YYYYMMDD') <= 20221016 AND TO_CHAR(END_DATE,'YYYYMMDD') >= 20221016 THEN '대여중'
        ELSE '대여 가능' END) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC