SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE LIKE '%세단%' AND TO_CHAR(B.START_DATE,'MM') LIKE '%10%'
ORDER BY A.CAR_ID DESC