SELECT MCDP_CD AS "진료과코드",COUNT(*) AS "5월예약건수"  
FROM APPOINTMENT 
WHERE 
    EXTRACT(YEAR FROM APNT_YMD) = 2022 AND EXTRACT(MONTH FROM APNT_YMD) = 5
    -- AND APNT_CNCL_YN = 'N' OR APNT_CNCL_YN IS NULL
GROUP BY MCDP_CD
ORDER BY "5월예약건수" ASC, MCDP_CD ASC
